AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket and DynamoDB for Terraform state files.
Parameters:
  S3BucketName: # tfstateファイルを保持するためのS3バケット名
    Type: String
    Description: Bucket name
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "[a-z0-9][a-zA-Z0-9.-]+"
  DynamoDBTableName: # ロック管理用のDynamoDBテーブル名
    Type: String
    Description: DynamoDB Table name
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "[a-zA-Z0-9][a-zA-Z0-9.-]+"
    Default: TerraformStateLockTable
  EnvironmentName:
    Type: String
    Description: Enrivonment name
    MinLength: 3
    MaxLength: 20
    AllowedPattern: "[a-zA-Z0-9][a-zA-Z0-9.-]+"
    Default: default
  ProductName:
    Type: String
    Description: Product name
    MinLength: 3
    MaxLength: 20
    AllowedPattern: "[a-zA-Z0-9][a-zA-Z0-9.-]+"
    Default: default
  TeamName:
    Type: String
    Description: Team name
    MinLength: 3
    MaxLength: 20
    AllowedPattern: "[a-zA-Z0-9][a-zA-Z0-9.-]+"
    Default: default
  Scope:
    Type: String
    Description: Scope
    MinLength: 3
    MaxLength: 20
    AllowedPattern: "[a-zA-Z0-9][a-zA-Z0-9.-]+"
    Default: default
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: S3BucketName
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration: # 過去のtfstateファイルをVersioningで保持する
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub |-
            Terraform backend S3 bucket for ${AWS::AccountId} by ${AWS::StackName}.
        - Key: Environment
          Value: 
            Ref: EnvironmentName
        - Key: Managed_by
          Value: 
            Ref: ProductName
        - Key: Team
          Value: 
            Ref: TeamName
        - Key: Scode
          Value: 
            Ref: Scope
        - Key: Product
          Value: 
            Ref: ProductName
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: DynamoDBTableName
      ProvisionedThroughput: # Terraformが利用するだけであれば読み書きパフォーマンスは最小で十分
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions: # ロック用列名(Terraformで決まっているので変更不可)
        -
          AttributeName: "LockID"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "LockID"
          KeyType: "HASH"
      Tags:
        - Key: Name
          Value: !Sub |-
            Terraform backend lock table for ${AWS::AccountId} by ${AWS::StackName}.
        - Key: Environment
          Value: 
            Ref: EnvironmentName
        - Key: Managed_by
          Value: 
            Ref: ProductName
        - Key: Team
          Value: 
            Ref: TeamName
        - Key: Scode
          Value: 
            Ref: Scope
        - Key: Product
          Value: 
            Ref: ProductName
